
services:
  app:
    user: "${USER_ID:- 1000}"
    hostname: "${HOST:- ml-project}"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USERNAME:-ramaaneesh}"
        USER_ID:  "${USER_ID:-1000}"
    image: mlproject-template
    container_name: mlproject-template
    volumes:
      - ./:/app/
      - ~/.config/gcloud:${HOME}/.config/gcloud
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
 
    ipc: host
    init: true  

